name: 📝 自动审核与合并笔记 PR

on:
  pull_request:
    types: [opened, reopened, synchronize]
  schedule:
    - cron: '0 4 * * 6'  # 每周六中午12:00 (UTC+8)，UTC时间为04:00
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check-and-merge:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 安装 jq
        run: sudo apt-get install -y jq

      - name: 获取 PR 文件列表
        id: files
        run: |
          files=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')
          echo "files<<EOF" >> $GITHUB_ENV
          echo "$files" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: 检查文件格式
        id: check
        run: |
          valid=true
          message=""
          for file in $files; do
            filename=$(basename "$file")
            if [[ ! $filename =~ ^2025413[0-9]{3}\.md$ ]]; then
              valid=false
              message+="❌ 文件名不符合要求: $filename\n"
              continue
            fi
            if [[ ! -f "$file" ]]; then
              valid=false
              message+="❌ 文件不存在: $file\n"
              continue
            fi
            # 检查 YAML 头
            header=$(head -n 10 "$file")
            if ! echo "$header" | grep -q "^---"; then
              valid=false
              message+="❌ 文件缺少 YAML 头: $filename\n"
              continue
            fi
            if ! echo "$header" | grep -q "title:"; then
              valid=false
              message+="❌ YAML 缺少 title 字段: $filename\n"
            fi
            if ! echo "$header" | grep -q "date:"; then
              valid=false
              message+="❌ YAML 缺少 date 字段: $filename\n"
            fi
            if ! echo "$header" | grep -q "tags: 笔记"; then
              valid=false
              message+="❌ YAML 缺少 tags: 笔记: $filename\n"
            fi
            if ! echo "$header" | grep -q "copyright_author:"; then
              valid=false
              message+="❌ YAML 缺少 copyright_author 字段: $filename\n"
            fi
          done

          echo "valid=$valid" >> $GITHUB_ENV
          echo "message=$message" >> $GITHUB_ENV

      - name: 处理结果
        run: |
          if [[ "$valid" == "true" ]]; then
            echo "✅ 格式检查通过，自动合并 PR"
            gh pr merge ${{ github.event.pull_request.number }} --merge --auto --delete-branch
          else
            echo -e "$message"
            gh pr comment ${{ github.event.pull_request.number }} --body "$message"
            gh pr close ${{ github.event.pull_request.number }}
          fi
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  weekly-report:
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 输出本周提交学号
        run: |
          echo "📘 本周提交的学号列表："
          git log --since="7 days ago" --pretty=format: --name-only \
            | grep '^2025413[0-9]\{3\}\.md$' | sort | uniq \
            | sed 's/\.md//' || echo "暂无提交"
