name: Auto Check & Merge Study Notes PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  validate-and-merge:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 设置 GitHub CLI 登录
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token
          gh auth status

      - name: 检查 PR 文件格式
        run: |
          echo "开始检查 PR #${{ github.event.pull_request.number }}"
          FILES=$(gh pr view ${{ github.event.pull_request.number }} --json files --jq '.files[].path')

          for file in $FILES; do
            echo "检查文件: $file"

            # 检查文件名是否符合要求
            if [[ ! $file =~ ^2025413[0-9]{3}\.md$ ]]; then
              echo "❌ 文件名不符合要求: $file"
              exit 1
            fi

            # 检查文件内容是否为 Markdown 且包含所需 YAML 头
            if ! grep -qE '^---' "$file"; then
              echo "❌ 缺少 YAML 头: $file"
              exit 1
            fi

            if ! grep -qE '^copyright_author:\s*[a-zA-Z0-9_-]+$' "$file"; then
              echo "❌ copyright_author 不合规"
              exit 1
            fi
          done

      - name: 自动合并符合要求的 PR
        if: success()
        run: |
          gh pr merge ${{ github.event.pull_request.number }} --merge --auto
